apiVersion: v1
kind: Service
metadata:
 name: mall-ums-svc
 namespace: default
spec:
  selector:
   app: mall-ums
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mall-ums
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mall-ums
    spec:
      containers:
      - name: mall-ums
        image: mall/mall-ums:1.0-SNAPSHOT
        ports:
        - containerPort: 8080