apiVersion: v1
kind: Service
metadata:
 name: mall-sms-svc
 namespace: default
spec:
  selector:
   app: mall-sms
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mall-sms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mall-sms
    spec:
      containers:
      - name: mall-sms
        image: mall/mall-sms:1.0-SNAPSHOT
        ports:
        - containerPort: 8080